// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOb_MlskN08pW1r6kHTedySoYq0FQVdDo',
    appId: '1:335231399324:web:4f8ef728a945f05c14c459',
    messagingSenderId: '335231399324',
    projectId: 'push-notification-26f2f',
    authDomain: 'push-notification-26f2f.firebaseapp.com',
    storageBucket: 'push-notification-26f2f.appspot.com',
    measurementId: 'G-Z2BM6K5GBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6dWL0jSyIeWVMo80bVvQEDotdyoIWMWY',
    appId: '1:335231399324:android:efd1e257a48749ca14c459',
    messagingSenderId: '335231399324',
    projectId: 'push-notification-26f2f',
    storageBucket: 'push-notification-26f2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASGn3FeSe1-o4gYBoFrE7qQ7XFNEO7Yrk',
    appId: '1:335231399324:ios:f0cf1599febf86c914c459',
    messagingSenderId: '335231399324',
    projectId: 'push-notification-26f2f',
    storageBucket: 'push-notification-26f2f.appspot.com',
    iosClientId: '335231399324-loq0alg4u3j4mqf9luvcrbemg2lsbdt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASGn3FeSe1-o4gYBoFrE7qQ7XFNEO7Yrk',
    appId: '1:335231399324:ios:100d9acd7c88642a14c459',
    messagingSenderId: '335231399324',
    projectId: 'push-notification-26f2f',
    storageBucket: 'push-notification-26f2f.appspot.com',
    iosClientId: '335231399324-v7nfvoeab30qrlft6keai9r7q8jtvkj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotification.RunnerTests',
  );
}
